// src/App.tsx
import React, { useState } from 'react';
import { HelmetProvider } from 'react-helmet-async';
import SEO from './components/SEO';
import Header from './components/Header';
import Hero from './components/Hero';
import Programs from './components/Programs';
import About from './components/About';
import Advertising from './components/Advertising';
import Contact from './components/Contact';
import Footer from './components/Footer';
import RadioPlayer from './components/RadioPlayer';
import AdminPanel from './components/AdminPanel';

function App() {
  const [isAdminOpen, setIsAdminOpen] = useState(false);

  return (
    <HelmetProvider>
      <div className="min-h-screen bg-dark-900 text-white font-inter">
        <SEO />
        <Header onAdminClick={() => setIsAdminOpen(true)} />
        <main>
          <Hero />
          <Programs />
          <About />
          <Advertising />
          <Contact />
        </main>
        <Footer />
        <RadioPlayer />
        <AdminPanel 
          isOpen={isAdminOpen} 
          onClose={() => setIsAdminOpen(false)} 
        />
      </div>
    </HelmetProvider>
  );
}

export default App;

// src/App.vue
<template>
  <div class="min-h-screen bg-dark-900 text-white font-inter">
    <SEO />
    <Header @admin-click="openAdmin" />
    <main>
      <Hero />
      <Programs />
      <About />
      <Advertising />
      <Contact />
    </main>
    <Footer />
    <RadioPlayer />
    <AdminPanel 
      :is-open="isAdminOpen" 
      @close="closeAdmin" 
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import SEO from './components/SEO.vue'
import Header from './components/Header.vue'
import Hero from './components/Hero.vue'
import Programs from './components/Programs.vue'
import About from './components/About.vue'
import Advertising from './components/Advertising.vue'
import Contact from './components/Contact.vue'
import Footer from './components/Footer.vue'
import RadioPlayer from './components/RadioPlayer.vue'
import AdminPanel from './components/AdminPanel.vue'

const isAdminOpen = ref(false)

const openAdmin = () => {
  isAdminOpen.value = true
}

const closeAdmin = () => {
  isAdminOpen.value = false
}
</script>
